name: Alerta Eneba TRY
on:
  schedule:
    - cron: '0 1,3,5,7 * * *'
    - cron: '0,30 8-23 * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python check_price.py
