name: Check Eneba prices (Premium TRY)

on:
  schedule:
       - cron: '3-58/5 * * * *'   # Cada 5 minutos
  workflow_dispatch:        # Por si quieres lanzarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Ejecutar script premium
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NOTIFY_SECRET: ${{ secrets.NOTIFY_SECRET }}
        run: python check_price_try.py
