name: Check Eneba prices (Premium TRY)

on:
  
  workflow_dispatch:        # Por si quieres lanzarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests

      # NUEVO: Paso intermedio con retraso aleatorio de 15 a 45 segundos
      - name: Espera aleatoria
        run: |
          RETRASO=$((RANDOM % 31 + 15))
          echo "Haciendo una pausa de $RETRASO segundos..."
          sleep $RETRASO

      - name: Ejecutar script premium
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NOTIFY_SECRET: ${{ secrets.NOTIFY_SECRET }}
        run: python check_price_try.py
